version: '3.8'
services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            -./init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
        
    python:
        build: .
        volumes:
            - .:/app
        depends_on:
            - postgres
        networks:
            - postgres-db-network

networks:
    postgres-db-network:
        driver: bridge