version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=MachineSimulator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      -  pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-db-network

  python:
    build: .
    volumes:
      - .:/main
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - postgres-db-network

networks:
  postgres-db-network:
    driver: bridge

volumes:
  pgdata: